name: mobile_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0" # adjust to your installed Dart SDK

dependencies:
  flutter:
    sdk: flutter

  # For making API calls
  http: ^1.2.1

  # For saving the auth token securely
  shared_preferences: ^2.2.3

  # For state management (to know if user is logged in)
  provider: ^6.1.2
  
  # This is a standard package, good to have
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # This is the correct place for your assets
  assets:
    - assets/images/